### ISSUE TITLE
data did not match any variant of untagged enum SchemaRef

### ISSUE THREAD

**Issue by teto** [blst-security/cherrybomb#100]
**Describe the bug**
with version 0.7.2: 
```
$ cherrybomb oas --file ~openapi.json
data did not match any variant of untagged enum SchemaRef
```
or with another command
```
cherrybomb param-table --file openapi.json
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum SchemaRef", line: 0, column: 0)', /home/teto/.cargo/registry/src/github.com-1ecc6299db9ec823/cherrybomb-swagger-0.1.1/src/tables/param_table.rs:206:62
```

sadly I can't share the openapi.json (i can extract a MWE if needed), I can say that https://editor.swagger.io/ detected tons of errors in our spec but I was looking for a local tool to install and check the results.

**Comment by OmerWow** [comment]
Hey @teto 

We would love to help you and improve Cherrybomb to better support your exact format!
Please join our [Discord channel](https://discord.gg/WdHhv4DqwU) and we'll try to figure out your problem privately, perhaps if you could show us only specific lines with censored/false info we could figure out the exact error we're facing here :)

**Comment by DeliciousBounty** [comment]
Hi @teto 
We just released a new version of CherryBomb, and the code should not panic on the table. rs (unwrap are removed).
I recommend that you test your OpenAPI file with the newer version. I see that you cannot share your file with us, so we cannot help you further. I will close this issue for the moment. If the issue is raised again, I invite you to open a new ticket.
